services:
  roommatch:
    container_name: roommatchcontainer
    build: 
      context: .
      args:
        CONTAINER_PORT: ${CONTAINER_PORT}
    image: roommatch:latest
    restart: unless-stopped
    env_file: 
      - ${ENV_FILE}
    expose:
      - ${CONTAINER_PORT}
    ports:
      - ${CONTAINER_PORT}:${HOST_PORT}
