spring:
    datasource:
        url: jdbc:mysql://localhost:3306/RoomMatch
        username: root
        password: 1234
    jpa:
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy:  org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl 
        show-sql: false
        properties:
            format-sql: true
        database: mysql
        database-platform: org.hibernate.dialect.MySQLDialect
    mail:
        host: localhost
        port: 1025
        username: raga
        password: raga
        properties:
            mail:
                smtp:
                    trust: "*"
                    auth: true
                    starttls:
                        enable: true
                    connectiontimeout: 5000
                    timeout: 3000
                    writetimeout: 5000

    