spring:
  datasource:
    url: jdbc:mysql://localhost:3306/RoomMatch
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    sql:
      init:
        mode: never
        continue-on-error: false