ACTIVE_PROFILE: dev
MYSQL_USERNAME: root
MYSQL_PASSWORD: 1234
MYSQL_HOST: localhost
MYSQL_PORT: 3306
MYSQL_DATABASE: RoomMatch
CONTAINER_PORT: 8080
MAIL_HOST: localhost
MAIL_PORT: 1025
MAIL_ID: raguzf
MAIL_PASSWORD: raguzf



    